### ISSUE TITLE
problem with requirements

### ISSUE THREAD

**Issue by userbox020** [y252328/THSR-captcha-solver#2]
Hello, i had this problem installing requirements

ERROR: Could not find a version that satisfies the requirement torch==1.3.0+cu92
 (from -r requirements.txt (line 7)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.p
ost2)
ERROR: No matching distribution found for torch==1.3.0+cu92 (from -r requirement
s.txt (line 7))

**Comment by y252328** [comment]
You may try to add `-f https://download.pytorch.org/whl/torch_stable.html` option when install pytorch(i.e., `pip3 install torch==1.3.0+cu92 torchvision==0.4.2+cu92 -f https://download.pytorch.org/whl/torch_stable.html`)

**Comment by userbox020** [comment]
thanks bro, It works, but i installed the cpu version because i dont have nvidia
